# Generated by Django 6.0.5 on 2026-05-13 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_message_is_delivered'),
        ('posts', '0009_camerafilter_reelaudio_storymusic_story_allow_music_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_in_messages', to='posts.reel'),
        ),
    ]
