# Generated by Django 6.0.5 on 2026-05-13 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_target_reel_alter_notification_verb'),
        ('posts', '0005_taggeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.story'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('share', 'shared your post'), ('reel_like', 'liked your reel'), ('story_reply', 'replied to your story'), ('story_view', 'viewed your story')], max_length=20),
        ),
    ]
