# Generated by Django 6.0.5 on 2026-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_verb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked your post'), ('comment', 'commented on your post'), ('follow', 'started following you'), ('share', 'shared your post'), ('reel_like', 'liked your reel'), ('reel_comment', 'commented on your reel'), ('reel_share', 'shared your reel'), ('story_reply', 'replied to your story'), ('story_view', 'viewed your story'), ('story_like', 'liked your story'), ('story_mention', 'mentioned you in a story')], max_length=20),
        ),
    ]
