# Generated by Django 6.0.5 on 2026-05-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_mutedstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='storymusic',
            name='language',
            field=models.CharField(blank=True, default='', help_text='e.g. Hindi, English, Korean, Punjabi', max_length=50),
        ),
        migrations.AddField(
            model_name='storymusic',
            name='lyrics',
            field=models.TextField(blank=True, default='', help_text='Song lyrics for display on story'),
        ),
    ]
