# Generated by Django 6.0.5 on 2026-05-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_storymusic_language_storymusic_lyrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('effect_type', models.CharField(choices=[('beauty', 'Beauty Filter'), ('ar', 'AR Effect'), ('video', 'Video Effect')], default='beauty', max_length=20)),
                ('css_filter', models.CharField(blank=True, default='', help_text='CSS filter string', max_length=300)),
                ('overlay_html', models.TextField(blank=True, default='', help_text='HTML for AR overlay element')),
                ('overlay_css', models.TextField(blank=True, default='', help_text='CSS for AR overlay')),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji icon', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['effect_type', 'order'],
            },
        ),
    ]
