# Generated by Django 6.0.5 on 2026-05-13 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_reelshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('css_filter', models.CharField(help_text='CSS filter string e.g. grayscale(100%)', max_length=200)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='filters/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReelAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='reel_audio/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='reel_audio/covers/')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in seconds')),
            ],
        ),
        migrations.CreateModel(
            name='StoryMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(blank=True, max_length=100)),
                ('audio_file', models.FileField(upload_to='story_music/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='story_music/covers/')),
                ('duration', models.PositiveIntegerField(default=30, help_text='Duration in seconds')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='allow_music',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='allow_reactions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='location_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='location_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='story',
            name='text_overlay_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='posts.reelaudio'),
        ),
        migrations.AddField(
            model_name='story',
            name='audio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='posts.storymusic'),
        ),
        migrations.CreateModel(
            name='StoryPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='posts.story')),
            ],
        ),
        migrations.CreateModel(
            name='StoryPollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.PositiveSmallIntegerField()),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.storypoll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poll', 'user')},
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='posts.story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('story', 'user', 'emoji')},
            },
        ),
    ]
