# Generated by Django 6.0.5 on 2026-05-14 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_camerafilter_reelaudio_storymusic_story_allow_music_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MutedStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_by_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_muted_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'muted_user')},
            },
        ),
    ]
