# Generated by Django 6.0.5 on 2026-05-11 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('posts', '0004_hashtag_post_video_reel_views_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_reel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.reel'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('like', 'liked'), ('comment', 'commented'), ('follow', 'followed'), ('share', 'shared'), ('reel_like', 'liked your reel'), ('story_reply', 'replied to your story')], max_length=20),
        ),
    ]
